# Generated by Django 3.1.1 on 2020-09-06 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200906_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 4, 42, 36, 242238, tzinfo=utc)),
        ),
    ]
